

CREATE TABLE BOOK(
Book_id INTEGER PRIMARY KEY,
Title VARCHAR(80) NOT NULL,
Publication_year INTEGER NOT NULL,
Gender varchar(30) NOT NULL,
Number_pages INTEGER NOT NULL,
Author_id INTEGER NOT NULL
);

CREATE TABLE AUTHOR(
Author_id INTEGER PRIMARY KEY,
"Name" varchar(80) NOT NULL,
Birthday DATE NOT NULL,
Hometown VARCHAR(65),
email VARCHAR(80) NOT NULL
);

ALTER TABLE BOOK ADD CONSTRAINT Author_Book FOREIGN KEY (Author_id) REFERENCES AUTHOR(Author_id);

